### ISSUE TITLE
Values wrote to registers being ignored on linux

### ISSUE THREAD

**Issue by ltsdw** [UraniumDonut/nbfc-revive#108]
It's not related to this project or any of the nbfc versions out there (at least I think so).

I have this Acer Nitro 5 AN515-57-520Y, and I can normally do something like this on Windows to make the cpu fan spin at 50%:

```
ec-probe.exe write 0x22 0x0c
ec-probe.exe write 0x37 0x32
```

But on Linux, while it alters the registers (I can read and monitor the values) it does nothing.

Someone could give me some ideas why this is happening? Alternatives, modules, etc?

I reported it here too if you want more details [nbfc-linux #65](https://github.com/nbfc-linux/nbfc-linux/issues/65)

**Comment by logan71f100** [comment]
im also having the same issue on latest version of pop os

**Comment by ltsdw** [comment]
closing, solved as of [#65 ](https://github.com/nbfc-linux/nbfc-linux/issues/65).
