### ISSUE TITLE
ec-probe monitor has a mismatch in the row and data comma structure when recording

### ISSUE THREAD

**Issue by jwhendy** [UraniumDonut/nbfc-revive#39]
**Describe the bug**
Here is an excerpt from `ec-probe monitor` on my computer showing that the header row does not end in a comma, but the data rows do:

```
$ cat Desktop/ec-monitor.txt 
2E,2F,32,35,36,47,4A,4B,52,62,97,9D,9F,A5,A9,AB,AF,B8,D0,D3,D4,D9,DA,E0
FF,FF,30,FF,FF,39,16,F9,22,00,18,A1,AD,63,17,1A,03,00,4A,2A,21,EF,10,13,
FF,FF,38,FF,FF,39,16,F9,26,00,18,A2,AD,62,17,1B,03,00,4A,2A,21,FB,04,13,
FF,FF,34,FF,FF,39,16,F9,03,00,18,A1,AD,64,17,1B,03,00,4A,7B,1F,D8,27,13,
```

It seems that the csv format may vary, but here is [one specification](https://datatracker.ietf.org/doc/html/rfc4180#page-2) which calls out:

> Each record is located on a separate line, delimited by a line break (CRLF).

The data rows are deliminted by a final comma and _then_ a line break.

I'm not sure what [this document](http://www.star.bris.ac.uk/~mbt/topcat/sun253/inCsv.html) is, but here are some other applicable rules speaking to this:

>The rules for [csv] data which it understands are as follows:
> - Each row must have the same number of comma-separated fields.
> - Adjacent commas, or a comma at the start or end of a line (whitespace apart) indicates a null field.
>- The first line may be a header line containing column names rather than a row of data. Exactly the same syntactic rules are followed for such a row as for data rows.

The output generated by `ec-probe monitor` essentially creates an empty/extra null column by ending each data row with a comma. In `python` using `pandas` this causes the first column to be used as the data frame index, and the last register is populated with `NaN` values.

```
import pandas as pd
df = pd.read_csv("ec-monitor-test.txt")
```

![grab_2021-09-04_124300](https://user-images.githubusercontent.com/379357/132103674-864fe8ca-b6a2-40f2-8ae0-c854e3f06536.png)

In `R` when trying to read in the file, you get the following, and must either add a comma to the end of the header row (yielding a "ghost" NA column) or delete the trailing commas from all data rows.
```
> read.csv('~/Desktop/ec-monitor-test.txt')
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  duplicate 'row.names' are not allowed
```

**To Reproduce**
Collect data using `ec-probe monitor -r path/to/file` and the generated `file` will have improper comma delimiters which cause problems when subsequently reading the data in.

**Expected behavior**
The header row and data rows should have the same structure (i.e. `field_0, field_1, ..., field_n`). I think this was just an oversight, as the [code removes the final comma](https://github.com/UraniumDonut/nbfc-revive/blob/master/Core/NbfcProbe/Program.cs#L310) from the header row, but not data rows.

**System information**
```
$ uname -a
Linux vera 5.13.13-arch1-1 #1 SMP PREEMPT Thu, 26 Aug 2021 19:14:36 +0000 x86_64 GNU/Linux

$ nbfc --version
1.6.3.0
```

**Comment by UraniumDonut** [comment]
Fixed in #40
