### ISSUE TITLE
ASUS UX391U tested working with the UX310UAK profile

### ISSUE THREAD

**Issue by tobychui** [UraniumDonut/nbfc-revive#55]
I am opening this issue just to inform anyone who is using ASUS UX391U that I have tested the "Asus Zenbook UX310UAK" profile is working with UX391U. If you got an UX391U and cannot find the suitable profile for your laptop, just go with the UX310UAK profile. 

It would be nice if anyone can copy the config of the UX310UAK and rename it to UX391U to make it more clear for the UX391U users. Thanks so much for the author's work :)

**Comment by UraniumDonut** [comment]
Hey, does it work completely (temperatures and fan % correct) or does it only “somewhat” work?

If it works completely, I will add it as a config.

**Comment by UraniumDonut** [comment]
[added](https://github.com/UraniumDonut/nbfc-revive/commit/b3ad299dbb050154288a5c4e3d03032b24894d36)
