### ISSUE TITLE
i7-11800H - Radio Buttons jump from "Read-Only" to "Disabled" back and forth, no temp displayed

### ISSUE THREAD

**Issue by ThePhoenixCoding** [UraniumDonut/nbfc-revive#60]
**Describe the bug**
When starting nbfc, selecting a profile (selfmade and fitting or prebuilt for other model) and selecting "Read-Only" or "Enabled" the radio button will repeatedly jump to "Disabled" and "Read-Only". No temperature is displayed (0°C). The service can't be uninstalled easily as it will continuouisly start and kill a process.

**To Reproduce**
- Install latest nbfc version
- Start nbfc
- Select any profile
- Click on "Read-Only"

**Expected behavior**
- Correct CPU temp is shown
- NBFC will run in desired mode and can control the fans in "Enabled" mode

**System information**
 - Win10 19042
 - 1.71
 - Log: 
[Log.txt](https://github.com/UraniumDonut/nbfc-revive/files/7518840/Log.txt)

**Additional context**
Using the 2021 Gigabyte Aero 17. Gigabyte Control Center etc. are disabled. Problem might be related to other "nbfc restart" issues

**Comment by UraniumDonut** [comment]
As far as I understand this is, because the program and its libraries don’t support 11th gen intel yet. If you want to contribute see #27
