### ISSUE TITLE
Add a fan curve to the program

### ISSUE THREAD

**Issue by K4sum1** [UraniumDonut/nbfc-revive#61]
I like the idea of customizing how loud my laptop runs, but I sometimes forget that my fans are very high when shutting it down, or the fans are too low or off when doing something demanding. A fan curve similar to that of MSI Afterburner and other fan control programs would fix this. I could have my laptop run passively up to 50C, but kick the fan on when doing something demanding that goes above 50C.

**Comment by Callistemon** [comment]
You can do that by editing the config file of the existing model configuration you are using, and then switching into Auto mode with Enabled status.

**Comment by K4sum1** [comment]
So I've finally gotten around to doing that, and I have to say that it works quite well.
