### ISSUE TITLE
Service won't start on Windows 21H1; works fine in Linux

### ISSUE THREAD

**Issue by zorkpatrol** [UraniumDonut/nbfc-revive#62]
Faulting application name: NbfcService.exe, version: 1.7.1.0, time stamp: 0x61743fa0
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1348, time stamp: 0x76fcd692
Exception code: 0xe0434352
Fault offset: 0x0000000000034f69
Faulting process id: 0x4c4
Faulting application start time: 0x01d7d937661ba044
Faulting application path: C:\Program Files (x86)\NoteBook FanControl\NbfcService.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: b58c61d0-c399-46ef-a354-ec69a7b41cce
Faulting package full name: 
Faulting package-relative application ID:

**Comment by zorkpatrol** [comment]
The problem was with OpenHardWareMonitor. The solution is found in this thread:

https://github.com/UraniumDonut/nbfc-revive/issues/27

**Comment by UraniumDonut** [comment]
Same issue as in #27
