### ISSUE TITLE
NBFC-Revive apparently, doesn't work.

### ISSUE THREAD

**Issue by sasi2006166** [UraniumDonut/nbfc-revive#63]
**Describe the bug**
I own a pavilion gaming laptop 16, i was trying to make my config but everytime the program switches from read-only to disabled and viceversa after some seconds.

**To Reproduce**
- Download latest release of NBFC-Revive (When i wrote it, was 1.7.1)
- Try to use any config and see that the program will switch back.

**Expected behavior**
Working CPU temp sensor ( displays 0 degress celsius ).
Working fan control.

**System information**
 - Windows 11 21H2 (build 22000.318)
 - 1.7.1
 - Log: https://ghostbin.com/6Pbk7

**Additional context**
No additional context apart my hardware:
i5 10300H
16 gb ddr4 dual-channel 3200 Mhz
GTX 1650Ti

**Comment by basso314** [comment]
It is a problem of the underlying plugin OpenHardwareMonitorLib and not supported new CPU models. It is solved here #27

**Comment by sasi2006166** [comment]
Now it is even worse, after clicking "enabled" my pc simply did a shutdown procedure and won't boot on windows, when i reach logon it simply shutdowns, had to remove nbfc in safe mode.

**Comment by ThePhoenixCoding** [comment]
> Now it is even worse, after clicking "enabled" my pc simply did a shutdown procedure and won't boot on windows, when i reach logon it simply shutdowns, had to remove nbfc in safe mode.

Are you positive that you use a working profile for your device? Writing unfitting values into the EC can cause a lot of weird behaviour.

**Comment by UraniumDonut** [comment]
Same issue as in #27
