### ISSUE TITLE
Question - what features does this project add?

### ISSUE THREAD

**Issue by peddy22** [UraniumDonut/nbfc-revive#67]
Should I update to this from stock NBFC if it works fine? Is it just adding support for newer laptops? Thanks

**Comment by UraniumDonut** [comment]
This projects serves as the current continuation of nbfc. 

This includes community made updates of all kind. This includes:

- new configs for laptops
- updates to support new architectures
- Bug fixes
- Refractoring 


For the last few months this has mainly been laptop configs and a few small bug fixes. (For example log output)

There will be a big architecture update when I (or someone else) find out how to change the LibHardwareMon component.
